apiVersion: 1

datasources:
  - name: InfluxDB-SAAP
    uid: saap-influx
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: saap
    isDefault: true
    jsonData:
      httpMode: GET
      dbName: saap
